// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/event.proto

/*
Package loggingv1 is a generated protocol buffer package.

It is generated from these files:
	v1/event.proto

It has these top-level messages:
	Event
	RichEvent
*/
package loggingv1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event_EventType int32

const (
	Event_UNKNOWN Event_EventType = 0
	Event_TWEET   Event_EventType = 1
	Event_FOLLOW  Event_EventType = 2
	Event_LIKE    Event_EventType = 3
)

var Event_EventType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TWEET",
	2: "FOLLOW",
	3: "LIKE",
}
var Event_EventType_value = map[string]int32{
	"UNKNOWN": 0,
	"TWEET":   1,
	"FOLLOW":  2,
	"LIKE":    3,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}
func (Event_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RichEvent_EventType int32

const (
	RichEvent_UNKNOWN RichEvent_EventType = 0
	RichEvent_TWEET   RichEvent_EventType = 1
	RichEvent_FOLLOW  RichEvent_EventType = 2
	RichEvent_LIKE    RichEvent_EventType = 3
)

var RichEvent_EventType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TWEET",
	2: "FOLLOW",
	3: "LIKE",
}
var RichEvent_EventType_value = map[string]int32{
	"UNKNOWN": 0,
	"TWEET":   1,
	"FOLLOW":  2,
	"LIKE":    3,
}

func (x RichEvent_EventType) String() string {
	return proto.EnumName(RichEvent_EventType_name, int32(x))
}
func (RichEvent_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Event struct {
	Id        uint64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	EventType Event_EventType            `protobuf:"varint,3,opt,name=event_type,json=eventType,enum=logging.v1.Event_EventType" json:"event_type,omitempty"`
	UserId    uint64                     `protobuf:"varint,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Value     string                     `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Event) GetEventType() Event_EventType {
	if m != nil {
		return m.EventType
	}
	return Event_UNKNOWN
}

func (m *Event) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Event) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RichEvent struct {
	Id        uint64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	EventType RichEvent_EventType        `protobuf:"varint,3,opt,name=event_type,json=eventType,enum=logging.v1.RichEvent_EventType" json:"event_type,omitempty"`
	UserId    uint64                     `protobuf:"varint,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Value     string                     `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Url       string                     `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	ReplyTo   uint64                     `protobuf:"varint,11,opt,name=reply_to,json=replyTo" json:"reply_to,omitempty"`
}

func (m *RichEvent) Reset()                    { *m = RichEvent{} }
func (m *RichEvent) String() string            { return proto.CompactTextString(m) }
func (*RichEvent) ProtoMessage()               {}
func (*RichEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RichEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RichEvent) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RichEvent) GetEventType() RichEvent_EventType {
	if m != nil {
		return m.EventType
	}
	return RichEvent_UNKNOWN
}

func (m *RichEvent) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RichEvent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RichEvent) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RichEvent) GetReplyTo() uint64 {
	if m != nil {
		return m.ReplyTo
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "logging.v1.Event")
	proto.RegisterType((*RichEvent)(nil), "logging.v1.RichEvent")
	proto.RegisterEnum("logging.v1.Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterEnum("logging.v1.RichEvent_EventType", RichEvent_EventType_name, RichEvent_EventType_value)
}

func init() { proto.RegisterFile("v1/event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xc1, 0x6b, 0xc2, 0x30,
	0x14, 0xc6, 0x97, 0x6a, 0xd5, 0xbc, 0x82, 0x94, 0x30, 0x58, 0xe6, 0x0e, 0x16, 0x4f, 0x3d, 0x45,
	0x74, 0x27, 0x77, 0x18, 0x6c, 0xd0, 0x81, 0x28, 0x0a, 0xa5, 0x43, 0xd8, 0xa5, 0x54, 0x9b, 0x75,
	0x81, 0x6a, 0x4a, 0x4d, 0x0b, 0xfe, 0x51, 0xfb, 0xff, 0x76, 0x1c, 0xa6, 0xd6, 0xed, 0xb0, 0xdb,
	0xbc, 0x84, 0xf7, 0x92, 0x97, 0xdf, 0xfb, 0xbe, 0x0f, 0xba, 0xe5, 0x68, 0xc8, 0x4b, 0xbe, 0x53,
	0x2c, 0xcb, 0xa5, 0x92, 0x04, 0x52, 0x99, 0x24, 0x62, 0x97, 0xb0, 0x72, 0xd4, 0xeb, 0x27, 0x52,
	0x26, 0x29, 0x1f, 0xea, 0x97, 0x75, 0xf1, 0x3e, 0x54, 0x62, 0xcb, 0xf7, 0x2a, 0xda, 0x66, 0xd5,
	0xf0, 0xe0, 0x0b, 0x81, 0xe9, 0x1d, 0x3f, 0x93, 0x2e, 0x18, 0x22, 0xa6, 0xc8, 0x41, 0x6e, 0xd3,
	0x37, 0x44, 0x4c, 0x26, 0x00, 0x9b, 0x9c, 0x47, 0x8a, 0xc7, 0x61, 0xa4, 0xa8, 0xe1, 0x20, 0xd7,
	0x1a, 0xf7, 0x58, 0xc5, 0x63, 0x35, 0x8f, 0x05, 0x35, 0xcf, 0xc7, 0xa7, 0xe9, 0x27, 0x45, 0x1e,
	0x00, 0xb4, 0xa0, 0x50, 0x1d, 0x32, 0x4e, 0x1b, 0x0e, 0x72, 0xbb, 0xe3, 0x3b, 0xf6, 0x23, 0x8b,
	0xe9, 0x8d, 0xd5, 0x19, 0x1c, 0x32, 0xee, 0x63, 0x5e, 0x97, 0xe4, 0x06, 0xda, 0xc5, 0x9e, 0xe7,
	0xa1, 0x88, 0x69, 0x53, 0x6b, 0x69, 0x1d, 0xdb, 0x69, 0x4c, 0xae, 0xc1, 0x2c, 0xa3, 0xb4, 0xe0,
	0xd4, 0x74, 0x90, 0x8b, 0xfd, 0xaa, 0x19, 0x4c, 0x00, 0x9f, 0x31, 0xc4, 0x82, 0xf6, 0xeb, 0x62,
	0xb6, 0x58, 0xae, 0x16, 0xf6, 0x15, 0xc1, 0x60, 0x06, 0x2b, 0xcf, 0x0b, 0x6c, 0x44, 0x00, 0x5a,
	0x2f, 0xcb, 0xf9, 0x7c, 0xb9, 0xb2, 0x0d, 0xd2, 0x81, 0xe6, 0x7c, 0x3a, 0xf3, 0xec, 0xc6, 0xe0,
	0xd3, 0x00, 0xec, 0x8b, 0xcd, 0xc7, 0xc5, 0xed, 0x3f, 0xfe, 0x61, 0xbf, 0xff, 0xdb, 0xfe, 0x79,
	0xeb, 0x25, 0x22, 0x20, 0x36, 0x34, 0x8a, 0x3c, 0xa5, 0xa0, 0xef, 0x8e, 0x25, 0xb9, 0x85, 0x4e,
	0xce, 0xb3, 0xf4, 0x10, 0x2a, 0x49, 0x2d, 0x4d, 0x68, 0xeb, 0x3e, 0x90, 0xff, 0xc8, 0xeb, 0xd9,
	0x7a, 0xc3, 0x27, 0x0f, 0xe5, 0x68, 0xdd, 0xd2, 0x11, 0xdc, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x8f, 0xa1, 0x05, 0x10, 0x7d, 0x02, 0x00, 0x00,
}
